import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "hi" | "kn";

const translations: Record<Language, Record<string, string>> = {
  en: {
    // General
    goodMorning: "Good morning",
    goodAfternoon: "Good afternoon",
    goodEvening: "Good evening",
    // Home
    todaysHealthScore: "Today's Health Score",
    fromYesterday: "+3 from yesterday",
    accuracy: "Accuracy",
    available: "Available",
    features: "Features",
    findNearbyHospitals: "Find Nearby Hospitals",
    findNearbyHospitalsDesc: "Real-time location • Ratings • Navigate instantly",
    quickActions: "Quick Actions",
    viewAll: "View all",
    aiDiagnosis: "AI Diagnosis",
    smartHealthScan: "Smart health scan",
    medScanner: "Med Scanner",
    identifyMedicines: "Identify medicines",
    moodTrack: "Mood Track",
    musicTherapy: "Music therapy",
    hospitals: "Hospitals",
    findNearby: "Find nearby",
    emergency: "Emergency",
    quickSOS: "Quick SOS",
    recentActivity: "Recent Activity",
    welcome: "Welcome!",
    startByChecking: "Start by checking your mood",
    now: "Now",
    // Bottom Nav
    home: "Home",
    scanner: "Scanner",
    mood: "Mood",
    aiHub: "AI Hub",
    map: "Map",
    // Auth
    careFusion: "Care Fusion",
    yourAIHealthCompanion: "Your AI Health Companion",
    aiPoweredDiagnosis: "AI-Powered Diagnosis",
    securePrivate: "Secure & Private",
    instantResults: "Instant Results",
    welcomeBack: "Welcome Back",
    createAccount: "Create Account",
    resetPassword: "Reset Password",
    wellSendResetLink: "We'll send you a reset link",
    signInToDashboard: "Sign in to your health dashboard",
    startHealthJourney: "Start your health journey today",
    fullName: "Full Name",
    emailAddress: "Email Address",
    password: "Password",
    forgotPassword: "Forgot Password?",
    sendResetLink: "Send Reset Link",
    signIn: "Sign In",
    pleaseWait: "Please wait...",
    backToSignIn: "← Back to Sign In",
    newToCareFusion: "New to Care Fusion?",
    alreadyHaveAccount: "Already have an account?",
    checkEmail: "Check your email",
    resetLinkSent: "Password reset link sent!",
    accountCreated: "Account created!",
    checkEmailVerify: "Check your email to verify.",
    error: "Error",
    // Scanner
    smartScanner: "Smart Scanner",
    scannerDesc: "AI-powered medicine & prescription analysis",
    medicine: "💊 Medicine",
    prescription: "📋 Prescription",
    scanMedicineLabel: "Scan a medicine label or pill",
    scanPrescription: "Scan your prescription document",
    retake: "Retake",
    scan: "Scan",
    upload: "Upload",
    analyzingWithAI: "Analyzing with AI...",
    mayTakeFewSeconds: "This may take a few seconds",
    analysisComplete: "Analysis Complete",
    medicineID: "Medicine ID",
    identifyPill: "Identify any pill or tablet",
    prescriptionOCR: "Prescription OCR",
    extractTextRx: "Extract text from Rx",
    // Mood
    moodAndMusic: "Mood & Music",
    howAreYouFeeling: "How are you feeling today?",
    selectYourMood: "Select your mood",
    moodLogged: "Mood logged! 🎵",
    musicForMood: "Here's music for your mood",
    moodLoggedProfile: "Mood logged to your health profile!",
    musicFor: "Music for",
    happy: "Happy",
    calm: "Calm",
    stressed: "Stressed",
    sad: "Sad",
    angry: "Angry",
    tired: "Tired",
    loved: "Loved",
    sick: "Sick",
    excited: "Excited",
    allLanguages: "All",
    english: "English",
    hindi: "Hindi",
    kannada: "Kannada",
    marathi: "Marathi",
    filterByLanguage: "Filter by language",
    // Health Hub
    aiHealthHub: "AI Health Hub",
    healthHubDesc: "Intelligent health analysis powered by AI",
    symptomChecker: "Symptom Checker",
    symptomCheckerDesc: "Describe symptoms for AI health insights",
    injuryScanner: "Injury Scanner",
    injuryScannerDesc: "Upload a photo for first-aid guidance",
    reportAnalyzer: "Report Analyzer",
    reportAnalyzerDesc: "Upload reports for simple summaries",
    healthTips: "Health Tips",
    healthTipsDesc: "Personalized daily wellness tips",
    describeSymptoms: "Describe Your Symptoms",
    symptomsPlaceholder: "E.g., I have a headache, slight fever, and body aches for 2 days...",
    analyzing: "Analyzing...",
    analyzeSymptoms: "Analyze Symptoms",
    uploadInjuryPhoto: "Upload Injury Photo",
    tapToUpload: "Tap to upload or take photo",
    retakePhoto: "Retake Photo",
    takePhoto: "Take Photo",
    analyzeMedicalReport: "Analyze Medical Report",
    pasteText: "📝 Paste Text",
    uploadImage: "📸 Upload Image",
    reportPlaceholder: "Paste your lab report, blood test results, or medical notes here...",
    analyzeReport: "Analyze Report",
    personalizedHealthTips: "Personalized Health Tips",
    tipsPlaceholder: "Optional: Tell us about yourself (age, conditions, goals) for personalized tips...",
    generating: "Generating...",
    generateTips: "Generate Tips",
    aiAnalysis: "AI Analysis",
    disclaimer: "⚠️ AI health features are for informational purposes only. Always consult a qualified healthcare professional.",
    aiChat: "AI Chat",
    aiVision: "AI Vision",
    ocrAI: "OCR + AI",
    personalized: "Personalized",
    // Map
    nearbyHospitals: "Nearby Hospitals",
    locationDetected: "📍 Location detected — showing real results",
    findingLocation: "Finding your location...",
    openGoogleMaps: "Open Google Maps",
    viewAllOnMap: "View all hospitals on map",
    emergencySOS: "Emergency SOS — Call 911",
    searching: "Searching...",
    hospitalsFound: "Hospitals Found",
    findingHospitals: "Finding hospitals near you...",
    openNow: "Open Now",
    closed: "Closed",
    navigate: "Navigate",
    call: "Call",
    details: "Details",
    noHospitalsFound: "No hospitals found nearby. Try searching on Google Maps.",
    locationDenied: "Location access denied. Enable location to find hospitals near you.",
    geolocationNotSupported: "Geolocation not supported.",
    couldNotFetch: "Could not fetch nearby hospitals. Tap the map to search on Google Maps.",
    // Chat
    careFusionAI: "Care Fusion AI",
    remembersConversations: "Remembers your conversations",
    signInForMemory: "Sign in for memory",
    askAnything: "Ask me anything about health...",
    signInToChat: "Sign in to chat...",
    chatCleared: "Chat cleared! How can I help you?",
    signInToUseChat: "Please sign in to use the AI chat assistant.",
    sorryError: "Sorry, I couldn't process that. Please try again.",
    // Language
    language: "Language",
    profile: "Profile",
    editProfile: "Edit Profile",
    displayName: "Display Name",
    enterDisplayName: "Enter your display name",
    saveChanges: "Save Changes",
    profileUpdated: "Profile updated!",
    signOut: "Sign Out",
    continueWithGoogle: "Continue with Google",
    or: "OR",
  },
  hi: {
    goodMorning: "सुप्रभात",
    goodAfternoon: "नमस्कार",
    goodEvening: "शुभ संध्या",
    todaysHealthScore: "आज का स्वास्थ्य स्कोर",
    fromYesterday: "कल से +3",
    accuracy: "सटीकता",
    available: "उपलब्ध",
    features: "सुविधाएँ",
    findNearbyHospitals: "नज़दीकी अस्पताल खोजें",
    findNearbyHospitalsDesc: "रियल-टाइम लोकेशन • रेटिंग • तुरंत नेविगेट करें",
    quickActions: "त्वरित कार्य",
    viewAll: "सभी देखें",
    aiDiagnosis: "AI निदान",
    smartHealthScan: "स्मार्ट स्वास्थ्य स्कैन",
    medScanner: "दवा स्कैनर",
    identifyMedicines: "दवाइयाँ पहचानें",
    moodTrack: "मूड ट्रैक",
    musicTherapy: "संगीत चिकित्सा",
    hospitals: "अस्पताल",
    findNearby: "नज़दीक खोजें",
    emergency: "आपातकालीन",
    quickSOS: "त्वरित SOS",
    recentActivity: "हाल की गतिविधि",
    welcome: "स्वागत है!",
    startByChecking: "अपना मूड जांचकर शुरू करें",
    now: "अभी",
    home: "होम",
    scanner: "स्कैनर",
    mood: "मूड",
    aiHub: "AI हब",
    map: "मैप",
    careFusion: "Care Fusion",
    yourAIHealthCompanion: "आपका AI स्वास्थ्य साथी",
    aiPoweredDiagnosis: "AI संचालित निदान",
    securePrivate: "सुरक्षित और निजी",
    instantResults: "तुरंत परिणाम",
    welcomeBack: "वापस स्वागत है",
    createAccount: "खाता बनाएँ",
    resetPassword: "पासवर्ड रीसेट",
    wellSendResetLink: "हम आपको रीसेट लिंक भेजेंगे",
    signInToDashboard: "अपने स्वास्थ्य डैशबोर्ड में साइन इन करें",
    startHealthJourney: "आज अपनी स्वास्थ्य यात्रा शुरू करें",
    fullName: "पूरा नाम",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड भूल गए?",
    sendResetLink: "रीसेट लिंक भेजें",
    signIn: "साइन इन",
    pleaseWait: "कृपया प्रतीक्षा करें...",
    backToSignIn: "← साइन इन पर वापस",
    newToCareFusion: "Care Fusion में नए हैं?",
    alreadyHaveAccount: "पहले से खाता है?",
    checkEmail: "अपना ईमेल जांचें",
    resetLinkSent: "पासवर्ड रीसेट लिंक भेजा गया!",
    accountCreated: "खाता बनाया गया!",
    checkEmailVerify: "सत्यापित करने के लिए अपना ईमेल जांचें।",
    error: "त्रुटि",
    smartScanner: "स्मार्ट स्कैनर",
    scannerDesc: "AI संचालित दवा और प्रिस्क्रिप्शन विश्लेषण",
    medicine: "💊 दवा",
    prescription: "📋 प्रिस्क्रिप्शन",
    scanMedicineLabel: "दवा का लेबल या गोली स्कैन करें",
    scanPrescription: "अपना प्रिस्क्रिप्शन दस्तावेज़ स्कैन करें",
    retake: "फिर से लें",
    scan: "स्कैन",
    upload: "अपलोड",
    analyzingWithAI: "AI से विश्लेषण हो रहा है...",
    mayTakeFewSeconds: "इसमें कुछ सेकंड लग सकते हैं",
    analysisComplete: "विश्लेषण पूर्ण",
    medicineID: "दवा पहचान",
    identifyPill: "किसी भी गोली या टैबलेट की पहचान करें",
    prescriptionOCR: "प्रिस्क्रिप्शन OCR",
    extractTextRx: "Rx से टेक्स्ट निकालें",
    moodAndMusic: "मूड और संगीत",
    howAreYouFeeling: "आज आप कैसा महसूस कर रहे हैं?",
    selectYourMood: "अपना मूड चुनें",
    moodLogged: "मूड दर्ज हो गया! 🎵",
    musicForMood: "आपके मूड के लिए संगीत",
    moodLoggedProfile: "मूड आपकी स्वास्थ्य प्रोफ़ाइल में दर्ज हो गया!",
    musicFor: "संगीत",
    happy: "खुश",
    calm: "शांत",
    stressed: "तनावग्रस्त",
    sad: "उदास",
    angry: "गुस्सा",
    tired: "थका हुआ",
    loved: "प्यार",
    sick: "बीमार",
    excited: "उत्साहित",
    allLanguages: "सभी",
    english: "अंग्रेज़ी",
    hindi: "हिंदी",
    kannada: "कन्नड़",
    marathi: "मराठी",
    filterByLanguage: "भाषा से फ़िल्टर करें",
    aiHealthHub: "AI स्वास्थ्य हब",
    healthHubDesc: "AI द्वारा संचालित बुद्धिमान स्वास्थ्य विश्लेषण",
    symptomChecker: "लक्षण जांचकर्ता",
    symptomCheckerDesc: "AI स्वास्थ्य अंतर्दृष्टि के लिए लक्षण बताएं",
    injuryScanner: "चोट स्कैनर",
    injuryScannerDesc: "प्राथमिक चिकित्सा मार्गदर्शन के लिए फोटो अपलोड करें",
    reportAnalyzer: "रिपोर्ट विश्लेषक",
    reportAnalyzerDesc: "सरल सारांश के लिए रिपोर्ट अपलोड करें",
    healthTips: "स्वास्थ्य सुझाव",
    healthTipsDesc: "व्यक्तिगत दैनिक कल्याण सुझाव",
    describeSymptoms: "अपने लक्षण बताएं",
    symptomsPlaceholder: "जैसे, मुझे 2 दिनों से सिरदर्द, हल्का बुखार और शरीर में दर्द है...",
    analyzing: "विश्लेषण हो रहा है...",
    analyzeSymptoms: "लक्षण विश्लेषण करें",
    uploadInjuryPhoto: "चोट की फोटो अपलोड करें",
    tapToUpload: "अपलोड या फोटो लेने के लिए टैप करें",
    retakePhoto: "फोटो फिर से लें",
    takePhoto: "फोटो लें",
    analyzeMedicalReport: "मेडिकल रिपोर्ट का विश्लेषण करें",
    pasteText: "📝 टेक्स्ट पेस्ट करें",
    uploadImage: "📸 छवि अपलोड करें",
    reportPlaceholder: "अपनी लैब रिपोर्ट, रक्त परीक्षण के परिणाम, या मेडिकल नोट्स यहां पेस्ट करें...",
    analyzeReport: "रिपोर्ट का विश्लेषण करें",
    personalizedHealthTips: "व्यक्तिगत स्वास्थ्य सुझाव",
    tipsPlaceholder: "वैकल्पिक: व्यक्तिगत सुझावों के लिए अपने बारे में बताएं (उम्र, स्थिति, लक्ष्य)...",
    generating: "उत्पन्न हो रहा है...",
    generateTips: "सुझाव उत्पन्न करें",
    aiAnalysis: "AI विश्लेषण",
    disclaimer: "⚠️ AI स्वास्थ्य सुविधाएँ केवल सूचनात्मक उद्देश्यों के लिए हैं। हमेशा योग्य स्वास्थ्य पेशेवर से परामर्श करें।",
    aiChat: "AI चैट",
    aiVision: "AI विज़न",
    ocrAI: "OCR + AI",
    personalized: "व्यक्तिगत",
    nearbyHospitals: "नज़दीकी अस्पताल",
    locationDetected: "📍 लोकेशन मिल गई — वास्तविक परिणाम दिखा रहे हैं",
    findingLocation: "आपकी लोकेशन खोज रहे हैं...",
    openGoogleMaps: "Google Maps खोलें",
    viewAllOnMap: "मैप पर सभी अस्पताल देखें",
    emergencySOS: "आपातकालीन SOS — 112 पर कॉल करें",
    searching: "खोज रहे हैं...",
    hospitalsFound: "अस्पताल मिले",
    findingHospitals: "आपके पास अस्पताल खोज रहे हैं...",
    openNow: "अभी खुला है",
    closed: "बंद",
    navigate: "नेविगेट",
    call: "कॉल",
    details: "विवरण",
    noHospitalsFound: "पास में कोई अस्पताल नहीं मिला। Google Maps पर खोजें।",
    locationDenied: "लोकेशन एक्सेस अस्वीकृत। अस्पताल खोजने के लिए लोकेशन सक्षम करें।",
    geolocationNotSupported: "जियोलोकेशन समर्थित नहीं है।",
    couldNotFetch: "अस्पताल नहीं मिल सके। Google Maps पर खोजें।",
    careFusionAI: "Care Fusion AI",
    remembersConversations: "आपकी बातचीत याद रखता है",
    signInForMemory: "मेमोरी के लिए साइन इन करें",
    askAnything: "स्वास्थ्य के बारे में कुछ भी पूछें...",
    signInToChat: "चैट करने के लिए साइन इन करें...",
    chatCleared: "चैट साफ़ हो गई! मैं आपकी कैसे मदद कर सकता हूँ?",
    signInToUseChat: "कृपया AI चैट सहायक का उपयोग करने के लिए साइन इन करें।",
    sorryError: "क्षमा करें, मैं इसे प्रोसेस नहीं कर सका। कृपया पुनः प्रयास करें।",
    language: "भाषा",
  },
  kn: {
    goodMorning: "ಶುಭೋದಯ",
    goodAfternoon: "ಶುಭ ಮಧ್ಯಾಹ್ನ",
    goodEvening: "ಶುಭ ಸಂಜೆ",
    todaysHealthScore: "ಇಂದಿನ ಆರೋಗ್ಯ ಸ್ಕೋರ್",
    fromYesterday: "ನಿನ್ನೆಗಿಂತ +3",
    accuracy: "ನಿಖರತೆ",
    available: "ಲಭ್ಯ",
    features: "ವೈಶಿಷ್ಟ್ಯಗಳು",
    findNearbyHospitals: "ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳನ್ನು ಹುಡುಕಿ",
    findNearbyHospitalsDesc: "ರಿಯಲ್-ಟೈಮ್ ಲೊಕೇಶನ್ • ರೇಟಿಂಗ್ • ತಕ್ಷಣ ನ್ಯಾವಿಗೇಟ್",
    quickActions: "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
    viewAll: "ಎಲ್ಲಾ ನೋಡಿ",
    aiDiagnosis: "AI ರೋಗನಿರ್ಣಯ",
    smartHealthScan: "ಸ್ಮಾರ್ಟ್ ಆರೋಗ್ಯ ಸ್ಕ್ಯಾನ್",
    medScanner: "ಔಷಧ ಸ್ಕ್ಯಾನರ್",
    identifyMedicines: "ಔಷಧಿಗಳನ್ನು ಗುರುತಿಸಿ",
    moodTrack: "ಮೂಡ್ ಟ್ರ್ಯಾಕ್",
    musicTherapy: "ಸಂಗೀತ ಚಿಕಿತ್ಸೆ",
    hospitals: "ಆಸ್ಪತ್ರೆಗಳು",
    findNearby: "ಹತ್ತಿರ ಹುಡುಕಿ",
    emergency: "ತುರ್ತು",
    quickSOS: "ತ್ವರಿತ SOS",
    recentActivity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
    welcome: "ಸ್ವಾಗತ!",
    startByChecking: "ನಿಮ್ಮ ಮೂಡ್ ಪರಿಶೀಲಿಸುವ ಮೂಲಕ ಪ್ರಾರಂಭಿಸಿ",
    now: "ಈಗ",
    home: "ಹೋಮ್",
    scanner: "ಸ್ಕ್ಯಾನರ್",
    mood: "ಮೂಡ್",
    aiHub: "AI ಹಬ್",
    map: "ಮ್ಯಾಪ್",
    careFusion: "Care Fusion",
    yourAIHealthCompanion: "ನಿಮ್ಮ AI ಆರೋಗ್ಯ ಸಹಚರ",
    aiPoweredDiagnosis: "AI ಚಾಲಿತ ರೋಗನಿರ್ಣಯ",
    securePrivate: "ಸುರಕ್ಷಿತ ಮತ್ತು ಖಾಸಗಿ",
    instantResults: "ತ್ವರಿತ ಫಲಿತಾಂಶಗಳು",
    welcomeBack: "ಮರಳಿ ಸ್ವಾಗತ",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    resetPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸಿ",
    wellSendResetLink: "ನಾವು ನಿಮಗೆ ಮರುಹೊಂದಿಸುವ ಲಿಂಕ್ ಕಳುಹಿಸುತ್ತೇವೆ",
    signInToDashboard: "ನಿಮ್ಮ ಆರೋಗ್ಯ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ",
    startHealthJourney: "ಇಂದು ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರಯಾಣ ಪ್ರಾರಂಭಿಸಿ",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    forgotPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?",
    sendResetLink: "ಮರುಹೊಂದಿಸುವ ಲಿಂಕ್ ಕಳುಹಿಸಿ",
    signIn: "ಸೈನ್ ಇನ್",
    pleaseWait: "ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ...",
    backToSignIn: "← ಸೈನ್ ಇನ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    newToCareFusion: "Care Fusion ಗೆ ಹೊಸಬರೇ?",
    alreadyHaveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
    checkEmail: "ನಿಮ್ಮ ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ",
    resetLinkSent: "ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸುವ ಲಿಂಕ್ ಕಳುಹಿಸಲಾಗಿದೆ!",
    accountCreated: "ಖಾತೆ ರಚಿಸಲಾಗಿದೆ!",
    checkEmailVerify: "ಪರಿಶೀಲಿಸಲು ನಿಮ್ಮ ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ.",
    error: "ದೋಷ",
    smartScanner: "ಸ್ಮಾರ್ಟ್ ಸ್ಕ್ಯಾನರ್",
    scannerDesc: "AI ಚಾಲಿತ ಔಷಧ ಮತ್ತು ಪ್ರಿಸ್ಕ್ರಿಪ್ಶನ್ ವಿಶ್ಲೇಷಣೆ",
    medicine: "💊 ಔಷಧ",
    prescription: "📋 ಪ್ರಿಸ್ಕ್ರಿಪ್ಶನ್",
    scanMedicineLabel: "ಔಷಧದ ಲೇಬಲ್ ಅಥವಾ ಮಾತ್ರೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    scanPrescription: "ನಿಮ್ಮ ಪ್ರಿಸ್ಕ್ರಿಪ್ಶನ್ ಡಾಕ್ಯುಮೆಂಟ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    retake: "ಮರು ತೆಗೆಯಿರಿ",
    scan: "ಸ್ಕ್ಯಾನ್",
    upload: "ಅಪ್‌ಲೋಡ್",
    analyzingWithAI: "AI ಮೂಲಕ ವಿಶ್ಲೇಷಣೆ...",
    mayTakeFewSeconds: "ಇದು ಕೆಲವು ಸೆಕೆಂಡುಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಬಹುದು",
    analysisComplete: "ವಿಶ್ಲೇಷಣೆ ಪೂರ್ಣ",
    medicineID: "ಔಷಧ ಗುರುತಿಸುವಿಕೆ",
    identifyPill: "ಯಾವುದೇ ಮಾತ್ರೆ ಅಥವಾ ಟ್ಯಾಬ್ಲೆಟ್ ಗುರುತಿಸಿ",
    prescriptionOCR: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಶನ್ OCR",
    extractTextRx: "Rx ನಿಂದ ಪಠ್ಯ ಹೊರತೆಗೆಯಿರಿ",
    moodAndMusic: "ಮೂಡ್ ಮತ್ತು ಸಂಗೀತ",
    howAreYouFeeling: "ಇಂದು ನೀವು ಹೇಗೆ ಅನುಭವಿಸುತ್ತಿದ್ದೀರಿ?",
    selectYourMood: "ನಿಮ್ಮ ಮೂಡ್ ಆಯ್ಕೆಮಾಡಿ",
    moodLogged: "ಮೂಡ್ ದಾಖಲಾಗಿದೆ! 🎵",
    musicForMood: "ನಿಮ್ಮ ಮೂಡ್‌ಗೆ ಸಂಗೀತ",
    moodLoggedProfile: "ಮೂಡ್ ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್‌ಗೆ ದಾಖಲಾಗಿದೆ!",
    musicFor: "ಸಂಗೀತ",
    happy: "ಸಂತೋಷ",
    calm: "ಶಾಂತ",
    stressed: "ಒತ್ತಡ",
    sad: "ದುಃಖ",
    angry: "ಕೋಪ",
    tired: "ಆಯಾಸ",
    loved: "ಪ್ರೀತಿ",
    sick: "ಅನಾರೋಗ್ಯ",
    excited: "ಉತ್ಸಾಹ",
    allLanguages: "ಎಲ್ಲಾ",
    english: "ಇಂಗ್ಲಿಷ್",
    hindi: "ಹಿಂದಿ",
    kannada: "ಕನ್ನಡ",
    marathi: "ಮರಾಠಿ",
    filterByLanguage: "ಭಾಷೆಯಿಂದ ಫಿಲ್ಟರ್ ಮಾಡಿ",
    aiHealthHub: "AI ಆರೋಗ್ಯ ಹಬ್",
    healthHubDesc: "AI ಚಾಲಿತ ಬುದ್ಧಿವಂತ ಆರೋಗ್ಯ ವಿಶ್ಲೇಷಣೆ",
    symptomChecker: "ಲಕ್ಷಣ ಪರಿಶೀಲಕ",
    symptomCheckerDesc: "AI ಆರೋಗ್ಯ ಒಳನೋಟಗಳಿಗಾಗಿ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ",
    injuryScanner: "ಗಾಯ ಸ್ಕ್ಯಾನರ್",
    injuryScannerDesc: "ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ ಮಾರ್ಗದರ್ಶನಕ್ಕಾಗಿ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    reportAnalyzer: "ವರದಿ ವಿಶ್ಲೇಷಕ",
    reportAnalyzerDesc: "ಸರಳ ಸಾರಾಂಶಗಳಿಗಾಗಿ ವರದಿಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    healthTips: "ಆರೋಗ್ಯ ಸಲಹೆಗಳು",
    healthTipsDesc: "ವೈಯಕ್ತಿಕ ದೈನಂದಿನ ಕ್ಷೇಮ ಸಲಹೆಗಳು",
    describeSymptoms: "ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ",
    symptomsPlaceholder: "ಉದಾ., ನನಗೆ 2 ದಿನಗಳಿಂದ ತಲೆನೋವು, ಸ್ವಲ್ಪ ಜ್ವರ ಮತ್ತು ಮೈಕೈ ನೋವು ಇದೆ...",
    analyzing: "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    analyzeSymptoms: "ಲಕ್ಷಣಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ",
    uploadInjuryPhoto: "ಗಾಯದ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    tapToUpload: "ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಅಥವಾ ಫೋಟೋ ತೆಗೆಯಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    retakePhoto: "ಫೋಟೋ ಮರು ತೆಗೆಯಿರಿ",
    takePhoto: "ಫೋಟೋ ತೆಗೆಯಿರಿ",
    analyzeMedicalReport: "ವೈದ್ಯಕೀಯ ವರದಿ ವಿಶ್ಲೇಷಿಸಿ",
    pasteText: "📝 ಪಠ್ಯ ಅಂಟಿಸಿ",
    uploadImage: "📸 ಚಿತ್ರ ಅಪ್‌ಲೋಡ್",
    reportPlaceholder: "ನಿಮ್ಮ ಲ್ಯಾಬ್ ವರದಿ, ರಕ್ತ ಪರೀಕ್ಷೆ ಫಲಿತಾಂಶ, ಅಥವಾ ವೈದ್ಯಕೀಯ ಟಿಪ್ಪಣಿಗಳನ್ನು ಇಲ್ಲಿ ಅಂಟಿಸಿ...",
    analyzeReport: "ವರದಿ ವಿಶ್ಲೇಷಿಸಿ",
    personalizedHealthTips: "ವೈಯಕ್ತಿಕ ಆರೋಗ್ಯ ಸಲಹೆಗಳು",
    tipsPlaceholder: "ಐಚ್ಛಿಕ: ವೈಯಕ್ತಿಕ ಸಲಹೆಗಳಿಗಾಗಿ ನಿಮ್ಮ ಬಗ್ಗೆ ಹೇಳಿ (ವಯಸ್ಸು, ಸ್ಥಿತಿ, ಗುರಿಗಳು)...",
    generating: "ಉತ್ಪಾದಿಸಲಾಗುತ್ತಿದೆ...",
    generateTips: "ಸಲಹೆಗಳನ್ನು ಉತ್ಪಾದಿಸಿ",
    aiAnalysis: "AI ವಿಶ್ಲೇಷಣೆ",
    disclaimer: "⚠️ AI ಆರೋಗ್ಯ ವೈಶಿಷ್ಟ್ಯಗಳು ಮಾಹಿತಿ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಮಾತ್ರ. ಯಾಮಾರೂ ಅರ್ಹ ಆರೋಗ್ಯ ವೃತ್ತಿಪರರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    aiChat: "AI ಚಾಟ್",
    aiVision: "AI ವಿಷನ್",
    ocrAI: "OCR + AI",
    personalized: "ವೈಯಕ್ತಿಕ",
    nearbyHospitals: "ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳು",
    locationDetected: "📍 ಲೊಕೇಶನ್ ಪತ್ತೆಯಾಗಿದೆ — ನಿಜವಾದ ಫಲಿತಾಂಶಗಳನ್ನು ತೋರಿಸುತ್ತಿದೆ",
    findingLocation: "ನಿಮ್ಮ ಲೊಕೇಶನ್ ಹುಡುಕುತ್ತಿದೆ...",
    openGoogleMaps: "Google Maps ತೆರೆಯಿರಿ",
    viewAllOnMap: "ಮ್ಯಾಪ್‌ನಲ್ಲಿ ಎಲ್ಲಾ ಆಸ್ಪತ್ರೆಗಳನ್ನು ನೋಡಿ",
    emergencySOS: "ತುರ್ತು SOS — 112 ಗೆ ಕರೆ ಮಾಡಿ",
    searching: "ಹುಡುಕುತ್ತಿದೆ...",
    hospitalsFound: "ಆಸ್ಪತ್ರೆಗಳು ಕಂಡುಬಂದಿವೆ",
    findingHospitals: "ನಿಮ್ಮ ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳನ್ನು ಹುಡುಕುತ್ತಿದೆ...",
    openNow: "ಈಗ ತೆರೆದಿದೆ",
    closed: "ಮುಚ್ಚಲಾಗಿದೆ",
    navigate: "ನ್ಯಾವಿಗೇಟ್",
    call: "ಕರೆ",
    details: "ವಿವರಗಳು",
    noHospitalsFound: "ಹತ್ತಿರ ಯಾವುದೇ ಆಸ್ಪತ್ರೆ ಕಂಡುಬಂದಿಲ್ಲ. Google Maps ನಲ್ಲಿ ಹುಡುಕಿ.",
    locationDenied: "ಲೊಕೇಶನ್ ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ. ಆಸ್ಪತ್ರೆ ಹುಡುಕಲು ಲೊಕೇಶನ್ ಸಕ್ರಿಯಗೊಳಿಸಿ.",
    geolocationNotSupported: "ಜಿಯೋಲೊಕೇಶನ್ ಬೆಂಬಲಿತವಾಗಿಲ್ಲ.",
    couldNotFetch: "ಆಸ್ಪತ್ರೆಗಳನ್ನು ಪಡೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. Google Maps ನಲ್ಲಿ ಹುಡುಕಿ.",
    careFusionAI: "Care Fusion AI",
    remembersConversations: "ನಿಮ್ಮ ಸಂಭಾಷಣೆಗಳನ್ನು ನೆನಪಿಟ್ಟುಕೊಳ್ಳುತ್ತದೆ",
    signInForMemory: "ಮೆಮೊರಿಗಾಗಿ ಸೈನ್ ಇನ್ ಮಾಡಿ",
    askAnything: "ಆರೋಗ್ಯದ ಬಗ್ಗೆ ಏನಾದರೂ ಕೇಳಿ...",
    signInToChat: "ಚಾಟ್ ಮಾಡಲು ಸೈನ್ ಇನ್ ಮಾಡಿ...",
    chatCleared: "ಚಾಟ್ ಅಳಿಸಲಾಗಿದೆ! ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?",
    signInToUseChat: "AI ಚಾಟ್ ಸಹಾಯಕವನ್ನು ಬಳಸಲು ದಯವಿಟ್ಟು ಸೈನ್ ಇನ್ ಮಾಡಿ.",
    sorryError: "ಕ್ಷಮಿಸಿ, ನಾನು ಅದನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    language: "ಭಾಷೆ",
  },
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem("app-language") as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = (key: string) => translations[language]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
